//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiAuth0App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_pt_PT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_pt_PT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiAuth0App.Resources.Languages.Language-pt-PT", typeof(Language_pt_PT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar valor.
        /// </summary>
        internal static string AddValue {
            get {
                return ResourceManager.GetString("AddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarmes.
        /// </summary>
        internal static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painéis.
        /// </summary>
        internal static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto realizado pelo quarto ano do instituto IISS Greppi Monticello, em colaboração com a Corvina cloud..
        /// </summary>
        internal static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O projecto foi desenvolvido usando .NET MAUI, e utiliza algumas bibliotecas adicionais:.
        /// </summary>
        internal static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação:.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAIDA.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última atualização.
        /// </summary>
        internal static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizações.
        /// </summary>
        internal static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alunos:.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Atributos.
        /// </summary>
        internal static string TagAttributes {
            get {
                return ResourceManager.GetString("TagAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers:.
        /// </summary>
        internal static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
    }
}
